### ISSUE TITLE
哥，qq空间显示登录错误

### ISSUE THREAD

**Issue by daylightsss** [crifan/BlogsToWordpress#2]
怎么办呀亲，救命呀

**Comment by crifan** [comment]
把

- 运行的命令和参数
- 详细的日志

都贴出来我看看呢

**Comment by Syaoran036** [comment]
我也是登陆不了QQ空间，疑似因为腾讯强制HTTPS的缘故？
`LINE 1611  INFO     Current runtime info:
LINE 1611  INFO     Paramenters       : ['E:\\BlogsToWordpress_x64.exe', '-s', 'http://473898521.qzone.qq.com']
LINE 1611  INFO     Python version    : sys.version_info(major=2, minor=7, micro=5, releaselevel='final', serial=0)
LINE 1611  INFO     platform.machine()=AMD64
LINE 1611  INFO     platform.node()=Tang-Qiming
LINE 1611  INFO     platform.platform()=Windows-7-6.1.7600
LINE 1611  INFO     platform.processor()=Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
LINE 1611  INFO     platform.python_build()=('default', 'May 15 2013 22:44:16')
LINE 1611  INFO     platform.python_compiler()=MSC v.1500 64 bit (AMD64)
LINE 1611  INFO     platform.python_branch()=
LINE 1611  INFO     platform.python_implementation()=CPython
LINE 1611  INFO     platform.python_revision()=
LINE 1611  INFO     platform.python_version()=2.7.5
LINE 1611  INFO     platform.python_version_tuple()=('2', '7', '5')
LINE 1611  INFO     platform.release()=7
LINE 1611  INFO     platform.system()=Windows
LINE 1611  INFO     platform.version()=6.1.7600
LINE 1611  INFO     platform.uname()=('Windows', 'Tang-Qiming', '7', '6.1.7600', 'AMD64', 'Intel64 Family 6 Model 158 Stepping 9, GenuineIntel')
LINE 1611  INFO     Default encoding  : ascii
LINE 1611  INFO     Current path      : C:\Users\QimingTang\AppData\Local\Temp\_MEI176402
LINE 1611  INFO     版本信息：v18.3
LINE 1611  INFO     1.如果脚本运行出错，请务必把上述(1)从脚本开始运行到上述所打印出来的系统信息(2)出错时候的相关信息(3)脚本所生成的BlogsToWordpress.log文件，通过复制粘贴、截图、附件等方式
LINE 1611  INFO       发送至admin(at)crifan.com或跟帖（下面有地址）回复，否则如果没有足够的错误相关信息，我就是想帮你解决问题，也没法帮啊！
LINE 1611  INFO     2.如对此脚本使用有任何疑问，请输入-h参数以获得相应的参数说明。
LINE 1611  INFO     3.关于本程序详细的使用说明和更多相关信息，请参考：
LINE 1611  INFO       BlogsToWordPress：将（新版）百度空间，网易163，新浪Sina，QQ空间，人人网，CSDN，搜狐Sohu，博客大巴Blogbus，天涯博客，点点轻博客等博客搬家到WordPress
LINE 1611  INFO       http://www.crifan.com/crifan_released_all/website/python/blogstowordpress/
LINE 1611  INFO     --------------------------------------------------------------------------------
LINE 1611  INFO     Your process type of post is: Export post to WXR(WordPress eXtended Rss).
LINE 1611  INFO     Source URL: http://473898521.qzone.qq.com
LINE 1619  DEBUG    Extracting blog user from url=http://473898521.qzone.qq.com
LINE 1611  INFO     Your blog provider : QQ Space.
LINE 1619  DEBUG    Now will call QQ Space function: extractBlogUser
LINE 1619  DEBUG    Extracting blog user from url=http://473898521.qzone.qq.com
LINE 1611  INFO     Extracted Blog user [473898521] from http://473898521.qzone.qq.com
LINE 1611  INFO     Blog entry url is http://user.qzone.qq.com/473898521/blog
LINE 1619  DEBUG    Set URL prefix for own   site picture: http://localhost/wp-content/uploads/pic
LINE 1619  DEBUG    Set URL prefix for other site picture: http://localhost/wp-content/uploads/pic/other_site
LINE 1611  INFO     Username and/or password is null, now in un-login mode.
LINE 1611  INFO     Now start to find the permanent link for http://473898521.qzone.qq.com
LINE 1619  DEBUG    Now will call QQ Space function: find1stPermalink
LINE 1619  DEBUG    postInYearUrl=http://b1.cnc.qzone.qq.com/cgi-bin/blognew/blog_get_datenum?oweruin=473898521&year=2005&r=0.76076681229&ref=qzone
LINE 1585  ERROR    Can not find the first link for http://473898521.qzone.qq.com, error=Unknown error!
LINE 1585  ERROR    Unknown Error !
Traceback (most recent call last):
  File "<string>", line 1989, in <module>
  File "<string>", line 1706, in main
SystemExit: 2
`
