### ISSUE TITLE
在windows下使用exe 以及在ubuntu中使用程序都无法进行到最后

### ISSUE THREAD

**Issue by Suiiiii** [crifan/BlogsToWordpress#3]
RT，也尝试过人人网，同样无法运行，之前给你写过邮件的

sui@ubuntu:~/Downloads/BlogsToWordpress-master$ python BlogsToWordpress.py
Imported: crifanLib,	v4.9
Imported: BlogNetease,	v1.7
Imported: BlogBaidu,	v3.5
Imported: BlogSina,	v1.6
Imported: BlogQQ,	v2.1
Imported: BlogCsdn,	v1.1
Imported: BlogSohu,	v1.3
2018/07/06 08:00:53 LINE 1445 INFO    Current runtime info:
2018/07/06 08:00:53 LINE 1446 INFO    Parameters       : ['BlogsToWordpress.py']
2018/07/06 08:00:53 LINE 1447 INFO    Python version    : sys.version_info(major=2, minor=7, micro=15, releaselevel='candidate', serial=1)
2018/07/06 08:00:53 LINE 1450 INFO    platform.machine()=x86_64
2018/07/06 08:00:53 LINE 1451 INFO    platform.node()=ubuntu
2018/07/06 08:00:53 LINE 1452 INFO    platform.platform()=Linux-4.15.0-23-generic-x86_64-with-Ubuntu-18.04-bionic
2018/07/06 08:00:53 LINE 1453 INFO    platform.processor()=x86_64
2018/07/06 08:00:53 LINE 1454 INFO    platform.python_build()=('default', 'Apr 15 2018 21:51:34')
2018/07/06 08:00:53 LINE 1455 INFO    platform.python_compiler()=GCC 7.3.0
2018/07/06 08:00:53 LINE 1456 INFO    platform.python_branch()=
2018/07/06 08:00:53 LINE 1457 INFO    platform.python_implementation()=CPython
2018/07/06 08:00:53 LINE 1458 INFO    platform.python_revision()=
2018/07/06 08:00:53 LINE 1459 INFO    platform.python_version()=2.7.15rc1
2018/07/06 08:00:53 LINE 1460 INFO    platform.python_version_tuple()=('2', '7', '15rc1')
2018/07/06 08:00:53 LINE 1461 INFO    platform.release()=4.15.0-23-generic
2018/07/06 08:00:53 LINE 1462 INFO    platform.system()=Linux
2018/07/06 08:00:53 LINE 1464 INFO    platform.version()=#25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018
2018/07/06 08:00:53 LINE 1465 INFO    platform.uname()=('Linux', 'ubuntu', '4.15.0-23-generic', '#25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018', 'x86_64', 'x86_64')
2018/07/06 08:00:53 LINE 1472 INFO    Default encoding  : ascii
2018/07/06 08:00:53 LINE 1473 INFO    Current path      : /usr
2018/07/06 08:00:53 LINE 1507 INFO    版本信息：v18.4
2018/07/06 08:00:53 LINE 1508 INFO    1.如果脚本运行出错，请务必把上述(1)从脚本开始运行到上述所打印出来的系统信息(2)出错时候的相关信息(3)脚本所生成的BlogsToWordpress.log文件，通过复制粘贴、截图、附件等方式
2018/07/06 08:00:53 LINE 1509 INFO      发送至admin(at)crifan.com或跟帖（下面有地址）回复，否则如果没有足够的错误相关信息，我就是想帮你解决问题，也没法帮啊！
2018/07/06 08:00:53 LINE 1510 INFO    2.如对此脚本使用有任何疑问，请输入-h参数以获得相应的参数说明。
2018/07/06 08:00:53 LINE 1511 INFO    3.关于本程序详细的使用说明和更多相关信息，请参考：
2018/07/06 08:00:53 LINE 1513 INFO      BlogsToWordPress：将（新版）百度空间，网易163，新浪Sina，QQ空间，人人网，CSDN，搜狐Sohu，博客大巴Blogbus，天涯博客，点点轻博客等博客搬家到WordPress
2018/07/06 08:00:53 LINE 1514 INFO      http://www.crifan.com/crifan_released_all/website/python/blogstowordpress/
2018/07/06 08:00:53 LINE 250  INFO    --------------------------------------------------------------------------------
2018/07/06 08:00:53 LINE 1555 INFO    Your process type of post is: Export post to WXR(WordPress eXtended Rss).
2018/07/06 08:00:53 LINE 1616 ERROR   Must designate the entry URL for the first blog item !
2018/07/06 08:00:53 LINE 1617 ERROR   解决办法：指定对应的-f或-s参数。详见：
2018/07/06 08:00:53 LINE 1618 ERROR   BlogsToWordPress 的用法的举例说明
2018/07/06 08:00:53 LINE 1619 ERROR   http://www.crifan.com/crifan_released_all/website/python/blogstowordpress/usage_example/
2018/07/06 08:00:53 LINE 1901 ERROR   Unknown Error !
Traceback (most recent call last):
  File "BlogsToWordpress.py", line 1899, in <module>
    main()
  File "BlogsToWordpress.py", line 1620, in main
    sys.exit(2);
SystemExit: 2
Traceback (most recent call last):
  File "BlogsToWordpress.py", line 1902, in <module>
    raise Exception("Unknown Error !")
Exception: Unknown Error !
sui@ubuntu:~/Downloads/BlogsToWordpress-master$ python BlogsToWordpress.py -s http://blog.sina.com.cn/u/5619285284 
Imported: crifanLib,	v4.9
Imported: BlogNetease,	v1.7
Imported: BlogBaidu,	v3.5
Imported: BlogSina,	v1.6
Imported: BlogQQ,	v2.1
Imported: BlogCsdn,	v1.1
Imported: BlogSohu,	v1.3
2018/07/06 08:01:06 LINE 1445 INFO    Current runtime info:
2018/07/06 08:01:06 LINE 1446 INFO    Parameters       : ['BlogsToWordpress.py', '-s', 'http://blog.sina.com.cn/u/5619285284']
2018/07/06 08:01:06 LINE 1447 INFO    Python version    : sys.version_info(major=2, minor=7, micro=15, releaselevel='candidate', serial=1)
2018/07/06 08:01:06 LINE 1450 INFO    platform.machine()=x86_64
2018/07/06 08:01:06 LINE 1451 INFO    platform.node()=ubuntu
2018/07/06 08:01:06 LINE 1452 INFO    platform.platform()=Linux-4.15.0-23-generic-x86_64-with-Ubuntu-18.04-bionic
2018/07/06 08:01:06 LINE 1453 INFO    platform.processor()=x86_64
2018/07/06 08:01:06 LINE 1454 INFO    platform.python_build()=('default', 'Apr 15 2018 21:51:34')
2018/07/06 08:01:06 LINE 1455 INFO    platform.python_compiler()=GCC 7.3.0
2018/07/06 08:01:06 LINE 1456 INFO    platform.python_branch()=
2018/07/06 08:01:06 LINE 1457 INFO    platform.python_implementation()=CPython
2018/07/06 08:01:06 LINE 1458 INFO    platform.python_revision()=
2018/07/06 08:01:06 LINE 1459 INFO    platform.python_version()=2.7.15rc1
2018/07/06 08:01:06 LINE 1460 INFO    platform.python_version_tuple()=('2', '7', '15rc1')
2018/07/06 08:01:06 LINE 1461 INFO    platform.release()=4.15.0-23-generic
2018/07/06 08:01:06 LINE 1462 INFO    platform.system()=Linux
2018/07/06 08:01:06 LINE 1464 INFO    platform.version()=#25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018
2018/07/06 08:01:06 LINE 1465 INFO    platform.uname()=('Linux', 'ubuntu', '4.15.0-23-generic', '#25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018', 'x86_64', 'x86_64')
2018/07/06 08:01:06 LINE 1472 INFO    Default encoding  : ascii
2018/07/06 08:01:06 LINE 1473 INFO    Current path      : /usr
2018/07/06 08:01:06 LINE 1507 INFO    版本信息：v18.4
2018/07/06 08:01:06 LINE 1508 INFO    1.如果脚本运行出错，请务必把上述(1)从脚本开始运行到上述所打印出来的系统信息(2)出错时候的相关信息(3)脚本所生成的BlogsToWordpress.log文件，通过复制粘贴、截图、附件等方式
2018/07/06 08:01:06 LINE 1509 INFO      发送至admin(at)crifan.com或跟帖（下面有地址）回复，否则如果没有足够的错误相关信息，我就是想帮你解决问题，也没法帮啊！
2018/07/06 08:01:06 LINE 1510 INFO    2.如对此脚本使用有任何疑问，请输入-h参数以获得相应的参数说明。
2018/07/06 08:01:06 LINE 1511 INFO    3.关于本程序详细的使用说明和更多相关信息，请参考：
2018/07/06 08:01:06 LINE 1513 INFO      BlogsToWordPress：将（新版）百度空间，网易163，新浪Sina，QQ空间，人人网，CSDN，搜狐Sohu，博客大巴Blogbus，天涯博客，点点轻博客等博客搬家到WordPress
2018/07/06 08:01:06 LINE 1514 INFO      http://www.crifan.com/crifan_released_all/website/python/blogstowordpress/
2018/07/06 08:01:06 LINE 250  INFO    --------------------------------------------------------------------------------
2018/07/06 08:01:06 LINE 1555 INFO    Your process type of post is: Export post to WXR(WordPress eXtended Rss).
2018/07/06 08:01:06 LINE 1601 INFO    Source URL: http://blog.sina.com.cn/u/5619285284
2018/07/06 08:01:06 LINE 1786 INFO    Your blog provider : Sina Blog.
2018/07/06 08:01:06 LINE 1406 INFO    Extracted Blog user [5619285284] from http://blog.sina.com.cn/u/5619285284
2018/07/06 08:01:06 LINE 1407 INFO    Blog entry url is http://blog.sina.com.cn/u/5619285284
2018/07/06 08:01:06 LINE 1385 INFO    Username and/or password is null, now in un-login mode.
2018/07/06 08:01:06 LINE 1606 INFO    Now start to find the permanent link for http://blog.sina.com.cn/u/5619285284
2018/07/06 08:01:09 LINE 1610 INFO    Found the first link http://blog.sina.com.cn/s/blog_14eef7d240102xb3l.html
2018/07/06 08:01:09 LINE 272  INFO    Current output folder: /home/sui/Downloads/BlogsToWordpress-master/output/5619285284
2018/07/06 08:01:09 LINE 1441 INFO    Generated WXR safe username is 5619285284
2018/07/06 08:01:09 LINE 1635 INFO    Generating wxr head info ...
2018/07/06 08:01:09 LINE 1298 INFO    Get blog head info OK
2018/07/06 08:01:09 LINE 1054 INFO    Generate wxr header OK
2018/07/06 08:01:09 LINE 1639 INFO    Generating generator info ...
2018/07/06 08:01:09 LINE 1076 INFO    Generate generator OK
2018/07/06 08:01:09 LINE 1643 INFO    Generating tail info ...
2018/07/06 08:01:09 LINE 1091 INFO    Generate tail OK
2018/07/06 08:01:09 LINE 816  INFO    [0001] http://blog.sina.com.cn/s/blog_14eef7d240102xb3l.html
2018/07/06 08:01:10 LINE 895  INFO      Title = 欢迎您在新浪博客安家
2018/07/06 08:01:12 LINE 950  INFO        Extracted comments:    1
2018/07/06 08:01:19 LINE 595  INFO        Processed picture   1: http://simg.sinajs.cn/blog/images/newblog01.jpg
2018/07/06 08:01:19 LINE 595  INFO        Processed picture   2: http://simg.sinajs.cn/blog/images/newblog04.jpg
2018/07/06 08:01:19 LINE 595  INFO        Processed picture   3: http://simg.sinajs.cn/blog/images/newblog02.jpg
2018/07/06 08:01:19 LINE 595  INFO        Processed picture   4: http://simg.sinajs.cn/blog/images/newblog08.jpg
2018/07/06 08:01:19 LINE 595  INFO        Processed picture   5: http://simg.sinajs.cn/blog/images/newblog03.jpg
2018/07/06 08:01:19 LINE 816  INFO    [0002] http://blog.sina.com.cn/s/blog_14eef7d240102xb3n.html
2018/07/06 08:01:20 LINE 895  INFO      Title = 关于博客名字的解释
2018/07/06 08:01:25 LINE 816  INFO    [0003] http://blog.sina.com.cn/s/blog_14eef7d240102xb3w.html
2018/07/06 08:01:26 LINE 895  INFO      Title = 这一次来德国的吐槽以及工作第一天
2018/07/06 08:01:34 LINE 595  INFO        Processed picture   1: http://www.sinaimg.cn/uc/myshow/blog/misc/gif/E___6725EN00SIGG.gif
2018/07/06 08:01:39 LINE 816  INFO    [0004] http://blog.sina.com.cn/s/blog_14eef7d240102xb69.html
2018/07/06 08:01:40 LINE 895  INFO      Title = 2017年11月14日
2018/07/06 08:01:57 LINE 816  INFO    [0005] http://blog.sina.com.cn/s/blog_14eef7d240102xb9y.html
2018/07/06 08:01:58 LINE 895  INFO      Title = 2017年11月15日
2018/07/06 08:02:10 LINE 595  INFO        Processed picture   1: http://s1.sinaimg.cn/large/0068hWNCzy7fPTyNzu7cf
2018/07/06 08:02:12 LINE 816  INFO    [0006] http://blog.sina.com.cn/s/blog_14eef7d240102xbdb.html
2018/07/06 08:02:16 LINE 895  INFO      Title = 2017年11月17日
2018/07/06 08:02:19 LINE 595  INFO        Processed picture   1: http://s2.sinaimg.cn/bmiddle/0068hWNCzy7fRKcUA4991&amp;690
2018/07/06 08:02:19 LINE 595  INFO        Processed picture   2: http://s7.sinaimg.cn/bmiddle/0068hWNCzy7fRKd4TSCc6&amp;690
2018/07/06 08:02:19 LINE 816  INFO    [0007] http://blog.sina.com.cn/s/blog_14eef7d240102xbj9.html
2018/07/06 08:02:20 LINE 895  INFO      Title = 2017年11月17日
2018/07/06 08:02:27 LINE 816  INFO    [0008] http://blog.sina.com.cn/s/blog_14eef7d240102xbsk.html
2018/07/06 08:02:28 LINE 895  INFO      Title = 2017年11月22日
2018/07/06 08:02:32 LINE 595  INFO        Processed picture   1: http://s1.sinaimg.cn/large/0068hWNCzy7g0qpUiB7d5
2018/07/06 08:02:33 LINE 816  INFO    [0009] http://blog.sina.com.cn/s/blog_14eef7d240102xbty.html
2018/07/06 08:02:34 LINE 895  INFO      Title = 2017年11月23日
2018/07/06 08:02:36 LINE 595  INFO        Processed picture   1: http://s11.sinaimg.cn/bmiddle/0068hWNCzy7g1lHMW7M9a&amp;690
2018/07/06 08:02:36 LINE 816  INFO    [0010] http://blog.sina.com.cn/s/blog_14eef7d240102xbvf.html
2018/07/06 08:02:37 LINE 895  INFO      Title = 2017年11月23日
2018/07/06 08:02:39 LINE 595  INFO        Processed picture   1: http://s1.sinaimg.cn/large/0068hWNCzy7g2VDr6H680
2018/07/06 08:02:39 LINE 595  INFO        Processed picture   2: http://s1.sinaimg.cn/large/0068hWNCzy7g2VFuEk67e
2018/07/06 08:02:39 LINE 595  INFO        Processed picture   3: http://s1.sinaimg.cn/large/0068hWNCzy7g2VGWfCeae
2018/07/06 08:02:39 LINE 595  INFO        Processed picture   4: http://s1.sinaimg.cn/large/0068hWNCzy7g2VIqzdf11
2018/07/06 08:02:41 LINE 816  INFO    [0011] http://blog.sina.com.cn/s/blog_14eef7d240102xbx9.html
2018/07/06 08:02:42 LINE 895  INFO      Title = 2017年11月24日
2018/07/06 08:02:45 LINE 816  INFO    [0012] http://blog.sina.com.cn/s/blog_14eef7d240102xbz7.html
2018/07/06 08:02:46 LINE 895  INFO      Title = 2017年11月26日
2018/07/06 08:02:50 LINE 595  INFO        Processed picture   1: http://s1.sinaimg.cn/large/0068hWNCzy7g7Nt9Ogie2
2018/07/06 08:02:51 LINE 595  INFO        Processed picture   2: http://s1.sinaimg.cn/large/0068hWNCzy7g7NZIn28f0
2018/07/06 08:02:52 LINE 595  INFO        Processed picture   3: http://s1.sinaimg.cn/large/0068hWNCzy7g7O0qn4s20
2018/07/06 08:02:53 LINE 595  INFO        Processed picture   4: http://s1.sinaimg.cn/large/0068hWNCzy7g7O121lIc6
2018/07/06 08:02:55 LINE 595  INFO        Processed picture   5: http://s1.sinaimg.cn/large/0068hWNCzy7g7O1ELR3e5
2018/07/06 08:02:56 LINE 595  INFO        Processed picture   6: http://s1.sinaimg.cn/large/0068hWNCzy7g7O2xIhYa2
2018/07/06 08:02:57 LINE 595  INFO        Processed picture   7: http://s1.sinaimg.cn/large/0068hWNCzy7g7O3ELzkba
2018/07/06 08:02:58 LINE 595  INFO        Processed picture   8: http://s1.sinaimg.cn/large/0068hWNCzy7g7O4Xdx721
2018/07/06 08:03:00 LINE 595  INFO        Processed picture   9: http://s1.sinaimg.cn/large/0068hWNCzy7g7O6bzhU6a
2018/07/06 08:03:01 LINE 595  INFO        Processed picture  10: http://s1.sinaimg.cn/large/0068hWNCzy7g7O6EheJ75
2018/07/06 08:03:02 LINE 816  INFO    [0013] http://blog.sina.com.cn/s/blog_14eef7d240102xc70.html
2018/07/06 08:03:03 LINE 895  INFO      Title = 2017年12月03日
2018/07/06 08:03:06 LINE 816  INFO    [0014] http://blog.sina.com.cn/s/blog_14eef7d240102xc71.html
2018/07/06 08:03:06 LINE 895  INFO      Title = 2017年12月02日
2018/07/06 08:03:09 LINE 595  INFO        Processed picture   1: http://s1.sinaimg.cn/large/0068hWNCzy7gihfecx513
2018/07/06 08:03:09 LINE 595  INFO        Processed picture   2: http://s1.sinaimg.cn/large/0068hWNCzy7gihfvWuWbe
2018/07/06 08:03:09 LINE 595  INFO        Processed picture   3: http://s1.sinaimg.cn/large/0068hWNCzy7gihkQoxe6c
2018/07/06 08:03:09 LINE 595  INFO        Processed picture   4: http://s1.sinaimg.cn/large/0068hWNCzy7gihm0myN85
2018/07/06 08:03:09 LINE 595  INFO        Processed picture   5: http://s1.sinaimg.cn/large/0068hWNCzy7gihnZ5ESe2
2018/07/06 08:03:09 LINE 595  INFO        Processed picture   6: http://s1.sinaimg.cn/large/0068hWNCzy7gihp9kw8c0
2018/07/06 08:03:10 LINE 595  INFO        Processed picture   7: http://s1.sinaimg.cn/large/0068hWNCzy7gihqFu7B07
2018/07/06 08:03:10 LINE 816  INFO    [0015] http://blog.sina.com.cn/s/blog_14eef7d240102xcgz.html
2018/07/06 08:03:11 LINE 895  INFO      Title = 2017年12月13日
2018/07/06 08:03:14 LINE 816  INFO    [0016] http://blog.sina.com.cn/s/blog_14eef7d240102xclk.html
2018/07/06 08:03:15 LINE 895  INFO      Title = 2017年12月12日
2018/07/06 08:03:18 LINE 595  INFO        Processed picture   1: http://s1.sinaimg.cn/large/0068hWNCzy7gwVBiyIhe1
2018/07/06 08:03:18 LINE 595  INFO        Processed picture   2: http://s1.sinaimg.cn/large/0068hWNCzy7gC4aU2fl9f
2018/07/06 08:03:18 LINE 595  INFO        Processed picture   3: http://s1.sinaimg.cn/large/0068hWNCzy7gC4b8mCh0d
2018/07/06 08:03:19 LINE 816  INFO    [0017] http://blog.sina.com.cn/s/blog_14eef7d240102xcll.html
2018/07/06 08:03:20 LINE 895  INFO      Title = 2017年12月15日
2018/07/06 08:03:23 LINE 595  INFO        Processed picture   1: http://s1.sinaimg.cn/large/0068hWNCzy7gC4q5LmZc5
2018/07/06 08:03:25 LINE 595  INFO        Processed picture   2: http://s1.sinaimg.cn/large/0068hWNCzy7gC4qtCFq58
2018/07/06 08:03:27 LINE 595  INFO        Processed picture   3: http://s1.sinaimg.cn/large/0068hWNCzy7gC4qQm6R01
2018/07/06 08:03:28 LINE 595  INFO        Processed picture   4: http://s1.sinaimg.cn/large/0068hWNCzy7gC4rcaBn85
2018/07/06 08:03:31 LINE 595  INFO        Processed picture   5: http://s1.sinaimg.cn/large/0068hWNCzy7gC4rtsj7d9
2018/07/06 08:03:31 LINE 595  INFO        Processed picture   6: http://s1.sinaimg.cn/large/0068hWNCzy7gC4s8xT157
2018/07/06 08:03:31 LINE 595  INFO        Processed picture   7: http://s1.sinaimg.cn/large/0068hWNCzy7gC4skcsb23
2018/07/06 08:03:32 LINE 816  INFO    [0018] http://blog.sina.com.cn/s/blog_14eef7d240102xcu7.html
2018/07/06 08:03:33 LINE 895  INFO      Title = 2017年12月21日
2018/07/06 08:03:35 LINE 595  INFO        Processed picture   1: http://s1.sinaimg.cn/large/0068hWNCzy7gK8qkTmAd4
2018/07/06 08:03:36 LINE 816  INFO    [0019] http://blog.sina.com.cn/s/blog_14eef7d240102xdlv.html
2018/07/06 08:03:37 LINE 895  INFO      Title = 2018年01月04日
2018/07/06 08:03:49 LINE 816  INFO    [0020] http://blog.sina.com.cn/s/blog_14eef7d240102xdui.html
2018/07/06 08:03:50 LINE 895  INFO      Title = 2018年01月05日
2018/07/06 08:03:53 LINE 595  INFO        Processed picture   1: http://s1.sinaimg.cn/large/0068hWNCzy7h88FgF7jf9
2018/07/06 08:03:54 LINE 816  INFO    [0021] http://blog.sina.com.cn/s/blog_14eef7d240102xdw2.html
2018/07/06 08:03:54 LINE 895  INFO      Title = 2018年01月05日
2018/07/06 08:03:58 LINE 816  INFO    [0022] http://blog.sina.com.cn/s/blog_14eef7d240102xe9i.html
2018/07/06 08:03:59 LINE 895  INFO      Title = 2018年01月12日
2018/07/06 08:04:03 LINE 595  INFO        Processed picture   1: http://s1.sinaimg.cn/large/0068hWNCzy7hkbyLaxs0a
2018/07/06 08:04:03 LINE 595  INFO        Processed picture   2: http://s1.sinaimg.cn/large/0068hWNCzy7hkbz8rKtbd
2018/07/06 08:04:04 LINE 595  INFO        Processed picture   3: http://s1.sinaimg.cn/large/0068hWNCzy7hkbzsY5xb7
2018/07/06 08:04:04 LINE 595  INFO        Processed picture   4: http://s1.sinaimg.cn/large/0068hWNCzy7hkbzjhhR4f
2018/07/06 08:04:14 LINE 816  INFO    [0023] http://blog.sina.com.cn/s/blog_14eef7d240102xeyl.html
2018/07/06 08:04:15 LINE 858  ERROR   Can not extract post title for http://blog.sina.com.cn/s/blog_14eef7d240102xeyl.html !
2018/07/06 08:04:15 LINE 1901 ERROR   Unknown Error !
Traceback (most recent call last):
  File "BlogsToWordpress.py", line 1899, in <module>
    main()
  File "BlogsToWordpress.py", line 1651, in main
    infoDict = fetchSinglePost(permalink);
  File "BlogsToWordpress.py", line 859, in fetchSinglePost
    sys.exit(2);
SystemExit: 2
Traceback (most recent call last):
  File "BlogsToWordpress.py", line 1902, in <module>
    raise Exception("Unknown Error !")
Exception: Unknown Error !

**Comment by crifan** [comment]
收到。不好意思，最近有点忙。我会尽快抽空修复的。🙏

**Comment by Suiiiii** [comment]
麻烦你了，客气的，
其实也没有多少数据，突然自己弄了个NAS 然后就弄了一下wordpress的事。
人人和新浪都不好用的。
我最开始是想因为我再国外的问题，所以可能因为地区原因所以无法使用，后来让朋友再国内实验了一下，也是不行。
